triggers:
- description: null
  envs: []
  last_enabled_at: 2025-09-25 21:42:10.258126+00:00
  name: GLOBAL_DATA_PRODUCT_TRIGGER
  pipeline_uuid: sql___python_workflow
  schedule_interval: null
  schedule_type: time
  settings: null
  sla: null
  start_time: null
  status: active
  token: 75989097810d465d8d01c44d3ab9ba1b
  variables: null
- description: null
  envs: []
  last_enabled_at: 2025-09-25 22:12:31.311759+00:00
  name: Hourly run after ingestion
  pipeline_uuid: sql___python_workflow
  schedule_interval: '@hourly'
  schedule_type: time
  settings:
    landing_time_enabled: true
  sla: null
  start_time: 2023-07-01 07:15:30+00:00
  status: active
  token: c900c247df7c4d4288e1e9d008427c22
  variables: {}
