triggers:
- description: null
  envs: []
  last_enabled_at: 2025-09-23 21:27:54.340518+00:00
  name: Run every 15 minutes
  pipeline_uuid: ingestion
  schedule_interval: '*/15 * * * *'
  schedule_type: time
  settings:
    landing_time_enabled: false
  sla: null
  start_time: 2025-09-23 21:27:00+00:00
  status: active
  token: fcc1402edbba49449505393b3c66c3f5
  variables: {}
