triggers:
- description: null
  envs: []
  last_enabled_at: 2025-09-23 21:41:21.580663+00:00
  name: API_TRIGGER_CREATED_FROM_CODE
  pipeline_uuid: dynamic_blocks_workflow
  schedule_interval: null
  schedule_type: api
  settings: null
  sla: null
  start_time: 2025-09-23 21:41:21.580516+00:00
  status: active
  token: 3e88ee3a4636481c9357fd71b10a9d7f
  variables: null
